### ISSUE TITLE
Steam Dark Mode Tool cmd

### ISSUE THREAD

**Issue by DmitriyPekar** [AikoMidori/steam-dark-mode#16]
does not work to update and replace

https://i.imgur.com/gwXlKWl.png

**Comment by AikoMidori** [comment]
I’ll look into it next week when i’m home after vacation

**Comment by DmitriyPekar** [comment]
> I’ll look into it next week when i’m home after vacation

Thanks

**Comment by AikoMidori** [comment]
> > I’ll look into it next week when i’m home after vacation
> 
> Thanks

may i kindly ask you to re-download the latest zip version from github and try again?
if the problem persists, please don't hesitate to let me know.

**Comment by DmitriyPekar** [comment]
downloaded the archive, unpacked it again and still has the same problem
