### ISSUE TITLE
Black Bar on Shop?

### ISSUE THREAD

**Issue by Caaine** [AikoMidori/steam-dark-mode#17]
https://puu.sh/EzBRb/71c75d0f3b.png

https://github.com/AikoMidori/steam-dark-mode/blob/26a849153b058a8d7cb722c2ed5af5569d22914e/steam-dark-mode-hard-edges/webkit.css#L204

div#footer,div#global_header,div#main,div#store_header,div.page_area{background:transparent!important}

**Comment by AikoMidori** [comment]
@Caaine Yes, a complete overhaul of the hard edges will be available soon with a lot of minor bug fixes, keep an eye open for the new update!

**Comment by AikoMidori** [comment]
@Caaine the hard edges is now up-to-date, enjoy!
