### ISSUE TITLE
Workshop hover info

### ISSUE THREAD

**Issue by BallOpener** [AikoMidori/steam-dark-mode#18]
I noticed that the dark mode skin isn't coloured correctly when hovering over the workshop items, it was in the default colours. It seems that they had recently added it in.
Here's some code:

`.hover_box{background:#353536!important;color:#b8b6b4!important}
.hover_arrow_inner {background:0 0!important}`

It does the job.

**Comment by AikoMidori** [comment]
Thank you for addressing the missing code on the workshop, code has been added,
