### ISSUE TITLE
Minor Hovering info arrow on profile guides 

### ISSUE THREAD

**Issue by BallOpener** [AikoMidori/steam-dark-mode#20]
Here is some code to hide an arrow when you enter their guide section in their profile, and an arrow would appear when you hover over the icons/links.
`.hover_arrow_inner {background:0 0!important; display:none;}
.hover_arrow_left{display:none}`

Edit: I've also fixed a similar minor issue that could bother someone where the hover box isn't aligned correctly with the images and other containers on the Workshop and the guide page as well. 
`#workshop_item_hover{margin-top:1em!important;}`

**Comment by AikoMidori** [comment]
I will implement this, thanks for the feedback,
