### ISSUE TITLE
Batch file missing

### ISSUE THREAD

**Issue by Beniess** [AikoMidori/steam-dark-mode#28]
Where is the batch file?

**Comment by jonyroda97** [comment]
The way to install manually is pretty much easy.
Check [`Manual Installation`](https://github.com/AikoMidori/steam-dark-mode#manual-installation) on how to do it.

Where it says "drag the files", it means only the `webkit.css` file.

I will let this issue open for AikoMidori if he wants to add anything.

**Comment by Beniess** [comment]
Ah ok i was confused when it said "files" and the download gif has totally different files in it than what is is available here. Putting in the webkit.css didn't seem to work but I'll try it again tomorrow.

**Comment by Beniess** [comment]
Ok I tried it again but there is no `webkit.css` to replace and just draging it in the the recource folder doesnt seem to do anything.

**Comment by jonyroda97** [comment]
Are you using a skin with steam?
If yes you need to replace the file inside the resource folder on the skin folder.

For example:
I have the Metro Skin and i have to put the `webkit.css` inside the `resource` folder in the `Metro Skin` folder
![image](https://user-images.githubusercontent.com/8282833/126780551-50e2aa82-a01e-4b4e-8d58-1d7a6a7db939.png)

If you want, I can help you with a discord call or in the voice chat of the discord server that is on the README.

**Comment by Beniess** [comment]
I just installed version 0.1.0 and its now working fine for me. 
Im using metro for steam windows 11 patch (unofficial) and it doesnt seem to work with v0.1.1
