### ISSUE TITLE
Store Scroll bar

### ISSUE THREAD

**Issue by Sc0D** [AikoMidori/steam-dark-mode#32]
My store scroll bar is purple , is there any way i can change ?
I cant find

**Comment by jonyroda97** [comment]
Line 4 of the `webkit.css` file.
If changing the value doesn't make any change, please send a screenshot of what scrollbar you are trying to change.

**Comment by Sc0D** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/120685600/213450998-3da62d5e-da51-42d8-9f1b-9fee87c789ca.jpg)

**Comment by jonyroda97** [comment]
Did you change the line 4 of the `webkit.css` file?
You downloaded and moved the file inside the `steam\skins\<skin_name>\resource` folder but you need to change the value inside of it.

**Comment by Sc0D** [comment]
OMG i'm so sorry to bother you, my webkit.css file was different so i downloaded it, sorry again
